name: build-one

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package name without .sh
        required: true
        type: string

concurrency:
  group: ${{ vars.REPO_NAME }}-x86_64
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build-package.yml
    with:
      package: ${{ github.event.inputs.package }}
    secrets: inherit
