name: build-one

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package name without .sh
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build-package.yml
    with:
      package: ${{ github.event.inputs.package }}
    secrets: inherit

  publish:
    needs: build
    if: ${{ always() && !cancelled() }}
    uses: ./.github/workflows/_publish-staged.yml
    secrets: inherit
